version: "3.8"

services:
  backend-blue:
    container_name: backend-blue     
    image: ${CI_REGISTRY_IMAGE}/sausage-backend:${VERSION}
    restart: always
    environment:
      VIRTUAL_HOST: "backend"
      VIRTUAL_PORT: "8080"     
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATA_MONGODB_URI: ${REPORTS_MONGODB_URI}
    networks:
      - sausage-store
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6

  backend-green:
    container_name: backend-green          
    image: ${CI_REGISTRY_IMAGE}/sausage-backend:${VERSION}
    restart: always
    environment:
      VIRTUAL_HOST: "backend"
      VIRTUAL_PORT: "8080"
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATA_MONGODB_URI: ${REPORTS_MONGODB_URI}
    networks:
      - sausage-store
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6

 backend-report:
    image: $CI_REGISTRY_IMAGE/sausage-backend-report:$VERSION
    container_name: sausage-store-backend-report
    restart: always
    environment:
      PORT: 8080
      SPRING_DATA_MONGODB_URI: ${REPORTS_MONGODB_URI}
    networks:
      - sausage-store


  frontend:
    image: $CI_REGISTRY_IMAGE/sausage-frontend:$VERSION
    container_name: sausage-store-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store:
