version: "3.8"

services:
  backend-blue:
    image: $CI_REGISTRY_IMAGE/sausage-backend:$VERSION
    container_name: backend-blue
    environment:
      # Переменные из application.properties можно заменить переменными окружения
      VIRTUAL_HOST: "backend"
      VIRTUAL_PORT: "8080"
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATA_MONGODB_URI: ${REPORTS_MONGODB_URI}
    restart: always
    networks:
      - sausage-store
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6
  backend-green:
    image: $CI_REGISTRY_IMAGE/sausage-backend:$VERSION
    environment:
      # Переменные из application.properties можно заменить переменными окружения
      VIRTUAL_HOST: "backend"
      VIRTUAL_PORT: "8080"
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATA_MONGODB_URI: ${REPORTS_MONGODB_URI}
    restart: always
    networks:
      - sausage-store
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6
  backend-report:
    image: $CI_REGISTRY_IMAGE/sausage-backend-report:$VERSION
    restart: always
    environment:
      PORT: 8080
      SPRING_DATA_MONGODB_URI: ${REPORTS_MONGODB_URI}
    networks:
      - sausage-store
  frontend:
    image: $CI_REGISTRY_IMAGE/sausage-frontend:$VERSION
    restart: always
    environment:
        DEFAULT_HOST: "backend"
    ports:
      - "80:80"
    networks:
      - sausage-store
    volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  sausage-store: