include:
  - template: Security/SAST.gitlab-ci.yml
 
variables:
  SAST_EXPERIMENTAL_STRING: "HELLO SAST"
  VERSION: 1.0.${CI_PIPELINE_ID}
 
stages:
  - build
  - test
  - notify
  - release

build-backend-code-job:
  variables:
    # VERSION: 1.0.${CI_PIPELINE_ID}
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  stage: build
  cache:
    paths:
        - ${CI_PROJECT_DIR}/.m2/repository # для хранения зависимостей бэкенда  
  # only:
    # changes:
    # - backend/*/
  script:
    - cd backend
    - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository -Dversion.application=${VERSION}
  artifacts:
    paths:
      - backend/target/sausage-store-${VERSION}.jar
      - ${CI_PROJECT_DIR}/.m2/
      
semgrep-sast:
    stage: test
    variables:
        COMPILE: "false"
        SAST_JAVA_VERSION: 11
        MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository # не забудьте при сборке также указывать эту папку через аргумент -Dmaven.repo.local
    cache:
      paths:
        - ${CI_PROJECT_DIR}/.m2/repository
    needs:
        - job: build-backend-code-job

telegram-notification-backend:
  stage: notify
  script:
    - |
      if [[ "$CI_COMMIT_MESSAGE" == *"send notification"* ]]; then
        message="Александр Гааг собрал Backend \nАртефакт доступен по [ссылке]($CI_PROJECT_URL/-/jobs/artifacts/${CI_COMMIT_REF_NAME}/download?job=build-backend-code-job)"
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"chat_id\": \"-1002138916913\", \"text\": \"$message\", \"parse_mode\": \"markdown\"}" \
        https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage
      fi
  only:
    variables:
      - $CI_COMMIT_MESSAGE
      - $CI_PIPELINE_SOURCE
    # changes:
      # - backend/*
  needs:
    - job: build-backend-code-job

upload-backend-release:
  stage: release
  # only:
    # changes:
      # - backend/**/*
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - mvn deploy -DskipTests -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository -s settings.xml -Dversion.application=${VERSION}

trigger_job:
  trigger:
    include:
      - local: 'frontend/.gitlab-ci.yml'    