include:
  - template: Security/SAST.gitlab-ci.yml
 
variables:
  SAST_EXPERIMENTAL_STRING: "HELLO SAST"
 
stages:
  - build
  - test
  - notify

build-backend-code-job:
  stage: build  
  # only:
    # changes:
    # - backend/*/
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
      
semgrep-sast:
    stage: test
    variables:
        COMPILE: "false"
        SAST_JAVA_VERSION: 11
        MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository # не забудьте при сборке также указывать эту папку через аргумент -Dmaven.repo.local
    cache:
      paths:
        - ${CI_PROJECT_DIR}/.m2/repository
    needs:
        - job: build-backend-code-job
    rules:
        when: manual

telegram-notification-backend:
  stage: notify
  script:
    - |
      if [[ "$CI_COMMIT_MESSAGE" == *"send notification"* ]]; then
        message="Александр Гааг собрал Backend \nАртефакт доступен по [ссылке]($CI_PROJECT_URL/-/jobs/artifacts/${CI_COMMIT_REF_NAME}/download?job=build-backend-code-job)"
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"chat_id\": \"-1002138916913\", \"text\": \"$message\", \"parse_mode\": \"markdown\"}" \
        https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage
      fi
  only:
    variables:
      - $CI_COMMIT_MESSAGE
      - $CI_PIPELINE_SOURCE
    # changes:
      # - backend/*
  needs:
    - job: build-backend-code-job